2023-11-19 21:58:57,556 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-11-19 21:58:57,557 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\default.LAPTOP-GNE1HV1K\AppData\Roaming\Python\Python312\site-packages\instabot\bot\bot.py
2023-11-19 21:58:57,558 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-11-19 21:59:02,615 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2023-11-19 21:59:02,615 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-11-19 21:59:02,616 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-11-19 21:59:02,616 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2023-11-19 22:04:06,767 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2023-11-19 22:04:06,770 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"","status":"fail"}'
2023-11-19 22:04:06,771 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2023-11-19 22:04:06,772 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: 
2023-11-19 22:04:06,772 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: {}
2023-11-19 22:04:10,438 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2023-11-19 22:04:13,646 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2023-11-19 22:04:16,337 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
